development:
  dialect: postgres
  database: {{envOr "DB_NAME" "backend_server_development"}}
  user: {{envOr "DB_USER" "postgres"}}
  password: {{envOr "DB_PASSWORD" "postgres"}}
  host: {{envOr "DB_HOST" "127.0.0.1"}}
  pool: 15

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/backend_server_test?sslmode=disable"}}

production:
  dialect: postgres
  url: {{envOr "DATABASE_URL" ""}}
  pool: 15