development:
  dialect: postgres
  database: {{envOr "DB_NAME" "backend_server_development"}}
  user: {{envOr "DB_USER" "postgres"}}
  password: {{envOr "DB_PASSWORD" "postgres"}}
  host: {{envOr "DB_HOST" "127.0.0.1"}}
  pool: 15

production:
  dialect: postgres
  url: {{envOr "DATABASE_URL" ""}}
  pool: 15