ALTER TABLE registrants
ADD COLUMN IF NOT EXISTS nickname TEXT,
ADD COLUMN IF NOT EXISTS school_origin TEXT,
ADD COLUMN IF NOT EXISTS origin_city TEXT,
ADD COLUMN IF NOT EXISTS has_rohis_exp BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS twibbon_url TEXT;
