package actions

import (
	"fmt"
	"net/http"
	"strings"
	"time"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v6"
	"github.com/gobuffalo/x/responder"
	"golang.org/x/crypto/bcrypt"

	"backend_server/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Admin)
// DB Table: Plural (admins)
// Resource: Plural (Admins)
// Path: Plural (/admins)
// View Template Folder: Plural (/templates/admins/)

// AdminsResource is the resource for the Admin model
type AdminsResource struct {
	buffalo.Resource
}

// List gets all Admins. This function is mapped to the path
// GET /admins
func (v AdminsResource) List(c buffalo.Context) error {
	// Ambil koneksi database dari context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	admins := &models.Admins{}

	// Pagination
	q := PaginateFromContext(tx, c)

	search := strings.TrimSpace(c.Param("search"))
	if search == "" {
		search = strings.TrimSpace(c.Param("q"))
	}
	if search != "" {
		q = q.Where("LOWER(email) LIKE LOWER(?)", "%"+search+"%")
	}

	status := strings.TrimSpace(c.Param("status"))
	if status == "active" || status == "true" {
		q = q.Where("is_active = ?", true)
	} else if status == "inactive" || status == "false" {
		q = q.Where("is_active = ?", false)
	}

	q = q.Order("created_at DESC")

	// Ambil semua data Admins dari database
	if err := q.All(admins); err != nil {
		return Response(c, http.StatusInternalServerError, err.Error(), nil)
	}

	// Kembalikan response JSON menggunakan fungsi Response
	return Response(c, http.StatusOK, "Admins retrieved successfully", map[string]interface{}{
		"admins":     admins,
		"data":       admins,
		"pagination": q.Paginator,
	})
}


// Show gets the data for one Admin. This function is mapped to
// the path GET /admins/{admin_id}
func (v AdminsResource) Show(c buffalo.Context) error {
	// Ambil koneksi database dari context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Siapkan struct admin kosong
	admin := &models.Admin{}

	// Cari admin berdasarkan ID
	if err := tx.Find(admin, c.Param("admin_id")); err != nil {
		return Response(c, http.StatusNotFound, "Admin not found", nil)
	}

	// Return response JSON yang konsisten
	return Response(c, http.StatusOK, "Admin retrieved successfully", map[string]interface{}{
		"admin": admin,
	})
}


// Create adds a Admin to the DB. This function is mapped to the
// path POST /admins
func (v AdminsResource) Create(c buffalo.Context) error {
	// Buat struct kosong untuk Admin
	admin := &models.Admin{}

	// Bind data dari request body ke struct
	if err := c.Bind(admin); err != nil {
		return Response(c, http.StatusBadRequest, "Invalid request body", nil)
	}

	// Hash password sebelum disimpan
	hashedPassword, err := bcrypt.GenerateFromPassword([]byte(admin.Password), 10)
	if err != nil {
		return Response(c, http.StatusInternalServerError, "Failed to hash password", nil)
	}
	admin.Password = string(hashedPassword)

	// Ambil koneksi database dari context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return Response(c, http.StatusInternalServerError, "No database transaction found", nil)
	}

	// Validasi dan simpan ke database
	verrs, err := tx.ValidateAndCreate(admin)
	if err != nil {
		return Response(c, http.StatusInternalServerError, "Failed to create admin", nil)
	}

	// Jika validasi gagal
	if verrs.HasAny() {
		return Response(c, http.StatusUnprocessableEntity, "Validation failed", verrs)
	}

	// Jika berhasil dibuat
	return Response(c, http.StatusCreated, "Admin created successfully", admin)
}


// Update changes a Admin in the DB. This function is mapped to
// the path PUT /admins/{admin_id}
func (v AdminsResource) Update(c buffalo.Context) error {
	// Ambil koneksi database dari context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return Response(c, http.StatusInternalServerError, "No database transaction found", nil)
	}

	// Cari admin berdasarkan ID
	admin := &models.Admin{}
	if err := tx.Find(admin, c.Param("admin_id")); err != nil {
		return Response(c, http.StatusNotFound, "Admin not found", nil)
	}

	// Bind data baru ke struct admin
	if err := c.Bind(admin); err != nil {
		return Response(c, http.StatusBadRequest, "Invalid request body", nil)
	}

	// Hash password sebelum disimpan
	hashedPassword, err := bcrypt.GenerateFromPassword([]byte(admin.Password), 10)
	if err != nil {
		return Response(c, http.StatusInternalServerError, "Failed to hash password", nil)
	}
	admin.Password = string(hashedPassword)

	// Jalankan validasi dan update data
	verrs, err := tx.ValidateAndUpdate(admin)
	if err != nil {
		return Response(c, http.StatusInternalServerError, "Failed to update admin", nil)
	}

	// Jika ada error validasi
	if verrs.HasAny() {
		return Response(c, http.StatusUnprocessableEntity, "Validation failed", verrs)
	}

	// Jika berhasil diupdate
	return Response(c, http.StatusOK, "Admin updated successfully", admin)
}


// Destroy deletes a Admin from the DB. This function is mapped
// to the path DELETE /admins/{admin_id}
func (v AdminsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Admin
	admin := &models.Admin{}

	// To find the Admin the parameter admin_id is used.
	if err := tx.Find(admin, c.Param("admin_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(admin); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "admin.destroyed.success"))

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/admins")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(admin))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(admin))
	}).Respond(c)
}

// LoginHandler handles login requests
func (v AdminsResource) Login(c buffalo.Context) error {
	var input struct {
		Email    string `json:"email"`
		Password string `json:"password"`
	}
	if err := c.Bind(&input); err != nil {
		return c.Error(http.StatusBadRequest, err)
	}

	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	admin := &models.Admin{}
	if err := tx.Where("email = ?", input.Email).First(admin); err != nil {
		return Response(c, http.StatusInternalServerError, "Admin not found", nil)
	}

	if !admin.IsActive {
		return Response(c, http.StatusForbidden, "Admin account is inactive", nil)
	}

	if err := bcrypt.CompareHashAndPassword([]byte(admin.Password), []byte(input.Password)); err != nil {
		return Response(c, http.StatusInternalServerError, "Wrong password", nil)
	}

	// PENTING: Role "admin"
	token, err := JWTService.CreateJWTToken(admin.ID, "admin")
	if err != nil {
		return Response(c, http.StatusInternalServerError, "Error generating token", nil)
	}

	admin.LastLogin = time.Now()
	tx.Update(admin)

	data := map[string]interface{}{
		"admin_id":       admin.ID,
		"is_super_admin": admin.IsSuperAdmin,
		"is_active":      admin.IsActive,
		"token":          token,
	}

	return Response(c, http.StatusOK, "Login successfully", data)
}
