package actions

import (
	"io"
	"log"
	"net/http"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v6"
	"github.com/google/uuid"

	"backend_server/models"
	"backend_server/storage"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Article)
// DB Table: Plural (articles)
// Resource: Plural (Articles)
// Path: Plural (/articles)
// View Template Folder: Plural (/templates/articles/)

// ArticlesResource is the resource for the Article model
type ArticlesResource struct {
	buffalo.Resource
	storageService *storage.StorageService
}

func NewArticleResource() ArticlesResource {
	return ArticlesResource{
		storageService: storage.NewStorageService(),
	}
}

// List gets all Articles. This function is mapped to the path
// GET /articles
func (v ArticlesResource) List(c buffalo.Context) error {
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return Response(c, http.StatusInternalServerError, "Database connection not found", nil)
	}

	articles := &models.Articles{}
	q := tx.PaginateFromParams(c.Params())

	if err := q.All(articles); err != nil {
		return Response(c, http.StatusInternalServerError, "Failed to retrieve articles", nil)
	}

	return Response(c, http.StatusOK, "Articles retrieved successfully", articles)
}

// Show one article by ID
func (v ArticlesResource) Show(c buffalo.Context) error {
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return Response(c, http.StatusInternalServerError, "Database connection not found", nil)
	}

	article := &models.Article{}
	if err := tx.Find(article, c.Param("article_id")); err != nil {
		return Response(c, http.StatusNotFound, "Article not found", nil)
	}

	return Response(c, http.StatusOK, "Article retrieved successfully", article)
}

// Create a new article
func (v ArticlesResource) Create(c buffalo.Context) error {
	article := &models.Article{}

	if err := c.Bind(article); err != nil {
		return Response(c, http.StatusBadRequest, "Invalid article data", nil)
	}

	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return Response(c, http.StatusInternalServerError, "Database connection not found", nil)
	}

	verrs, err := tx.ValidateAndCreate(article)
	if err != nil {
		return Response(c, http.StatusInternalServerError, "Failed to create article", err)
	}
	if verrs.HasAny() {
		return Response(c, http.StatusUnprocessableEntity, "Validation error", verrs)
	}

	return Response(c, http.StatusCreated, "Article created successfully", article)
}

// Update an article
func (v ArticlesResource) Update(c buffalo.Context) error {
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return Response(c, http.StatusInternalServerError, "Database connection not found", nil)
	}

	article := &models.Article{}
	if err := tx.Find(article, c.Param("article_id")); err != nil {
		return Response(c, http.StatusNotFound, "Article not found", nil)
	}

	if err := c.Bind(article); err != nil {
		return Response(c, http.StatusBadRequest, "Invalid article data", nil)
	}

	verrs, err := tx.ValidateAndUpdate(article)
	if err != nil {
		return Response(c, http.StatusInternalServerError, "Failed to update article", nil)
	}
	if verrs.HasAny() {
		return Response(c, http.StatusUnprocessableEntity, "Validation error", verrs)
	}

	return Response(c, http.StatusOK, "Article updated successfully", article)
}

// Destroy (delete) an article
func (v ArticlesResource) Destroy(c buffalo.Context) error {
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return Response(c, http.StatusInternalServerError, "Database connection not found", nil)
	}

	article := &models.Article{}
	if err := tx.Find(article, c.Param("article_id")); err != nil {
		return Response(c, http.StatusNotFound, "Article not found", nil)
	}

	if article.ImgURL != "" {
		key := v.storageService.ExtractObjectKey(article.ImgURL, v.storageService.Bucket)

		if err := v.storageService.Delete(c.Request().Context(), key); err != nil {
			log.Printf("⚠️ gagal hapus file di MinIO: %v", err)
			// Tidak langsung return error — file bisa saja sudah hilang, tapi record tetap dihapus
		}
	}

	if err := tx.Destroy(article); err != nil {
		return Response(c, http.StatusInternalServerError, "Failed to delete article", nil)
	}

	return Response(c, http.StatusOK, "Article deleted successfully", nil)
}

func (v ArticlesResource) UploadImage(c buffalo.Context) error {
	file, err := c.File("image")
	if err != nil {
		return Response(c, http.StatusBadRequest, "failed to read image file", err.Error())
	}
	defer file.Close()

	buf, _ := io.ReadAll(file)

	url, err := v.storageService.Upload(c.Request().Context(), "articles/"+ uuid.New().String() + file.Filename, buf)
	if err != nil {
		return Response(c, http.StatusInternalServerError, "failed to upload image", err.Error())
	}

	return Response(c, http.StatusOK, "upload success", map[string]string{
		"url": url,
	})
}