package actions

import (
	"net/http"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v6"

	"backend_server/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (MediaCategory)
// DB Table: Plural (media_categories)
// Resource: Plural (MediaCategories)
// Path: Plural (/media_categories)
// View Template Folder: Plural (/templates/media_categories/)

// MediaCategoriesResource is the resource for the MediaCategory model
type MediaCategoriesResource struct {
	buffalo.Resource
}

// List gets all MediaCategories. This function is mapped to the path
// GET /media_categories
func (v MediaCategoriesResource) List(c buffalo.Context) error {
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return Response(c, http.StatusInternalServerError, "no transaction found", nil)
	}

	mediaCategories := &models.MediaCategories{}
	q := tx.PaginateFromParams(c.Params())

	if err := q.All(mediaCategories); err != nil {
		return Response(c, http.StatusInternalServerError, "failed to fetch media categories", err.Error())
	}

	return Response(c, http.StatusOK, "success", map[string]interface{}{
		"data":       mediaCategories,
	})
}

// Show - GET /media_categories/{media_category_id}
func (v MediaCategoriesResource) Show(c buffalo.Context) error {
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return Response(c, http.StatusInternalServerError, "no transaction found", nil)
	}

	mediaCategory := &models.MediaCategory{}
	if err := tx.Find(mediaCategory, c.Param("media_category_id")); err != nil {
		return Response(c, http.StatusNotFound, "media category not found", err.Error())
	}

	return Response(c, http.StatusOK, "success", mediaCategory)
}

// Create - POST /media_categories
func (v MediaCategoriesResource) Create(c buffalo.Context) error {
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return Response(c, http.StatusInternalServerError, "no transaction found", nil)
	}

	mediaCategory := &models.MediaCategory{}
	if err := c.Bind(mediaCategory); err != nil {
		return Response(c, http.StatusBadRequest, "invalid input", err.Error())
	}

	verrs, err := tx.ValidateAndCreate(mediaCategory)
	if err != nil {
		return Response(c, http.StatusInternalServerError, "failed to create media category", err.Error())
	}

	if verrs.HasAny() {
		return Response(c, http.StatusUnprocessableEntity, "validation errors", verrs)
	}

	return Response(c, http.StatusCreated, "media category created successfully", mediaCategory)
}

// Update - PUT /media_categories/{media_category_id}
func (v MediaCategoriesResource) Update(c buffalo.Context) error {
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return Response(c, http.StatusInternalServerError, "no transaction found", nil)
	}

	mediaCategory := &models.MediaCategory{}
	if err := tx.Find(mediaCategory, c.Param("media_category_id")); err != nil {
		return Response(c, http.StatusNotFound, "media category not found", err.Error())
	}

	if err := c.Bind(mediaCategory); err != nil {
		return Response(c, http.StatusBadRequest, "invalid input", err.Error())
	}

	verrs, err := tx.ValidateAndUpdate(mediaCategory)
	if err != nil {
		return Response(c, http.StatusInternalServerError, "failed to update media category", err.Error())
	}

	if verrs.HasAny() {
		return Response(c, http.StatusUnprocessableEntity, "validation errors", verrs)
	}

	return Response(c, http.StatusOK, "media category updated successfully", mediaCategory)
}

// Destroy - DELETE /media_categories/{media_category_id}
func (v MediaCategoriesResource) Destroy(c buffalo.Context) error {
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return Response(c, http.StatusInternalServerError, "no transaction found", nil)
	}

	mediaCategory := &models.MediaCategory{}
	if err := tx.Find(mediaCategory, c.Param("media_category_id")); err != nil {
		return Response(c, http.StatusNotFound, "media category not found", err.Error())
	}

	if err := tx.Destroy(mediaCategory); err != nil {
		return Response(c, http.StatusInternalServerError, "failed to delete media category", err.Error())
	}

	return Response(c, http.StatusOK, "media category deleted successfully", nil)
}