package actions

import (
	"io"
	"log"
	"net/http"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v6"
	"github.com/google/uuid"

	"backend_server/models"
	"backend_server/storage"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Media)
// DB Table: Plural (media)
// Resource: Plural (Media)
// Path: Plural (/media)
// View Template Folder: Plural (/templates/media/)

// MediaResource is the resource for the Media model
type MediaResource struct {
	buffalo.Resource
	storageService *storage.StorageService
}

func NewMediaResource() MediaResource {
	return MediaResource{
		storageService: storage.NewStorageService(),
	}
}

// List gets all Media. This function is mapped to the path
// GET /media
func (v MediaResource) List(c buffalo.Context) error {
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return Response(c, http.StatusInternalServerError, "no transaction found", nil)
	}

	media := &[]models.Media{}
	q := tx.PaginateFromParams(c.Params())

	if err := q.All(media); err != nil {
		return Response(c, http.StatusInternalServerError, "failed to retrieve media", err.Error())
	}

	return Response(c, http.StatusOK, "success", map[string]interface{}{
		"media":      media,
		"pagination": q.Paginator,
	})
}

// Show menampilkan satu data media berdasarkan ID
func (v MediaResource) Show(c buffalo.Context) error {
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return Response(c, http.StatusInternalServerError, "no transaction found", nil)
	}

	media := &models.Media{}
	if err := tx.Find(media, c.Param("media_id")); err != nil {
		return Response(c, http.StatusNotFound, "media not found", err.Error())
	}

	return Response(c, http.StatusOK, "success", media)
}

// Create menambah media baru
func (v MediaResource) Create(c buffalo.Context) error {
	media := &models.Media{}
	if err := c.Bind(media); err != nil {
		return Response(c, http.StatusBadRequest, "invalid request body", err.Error())
	}

	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return Response(c, http.StatusInternalServerError, "no transaction found", nil)
	}

	verrs, err := tx.ValidateAndCreate(media)
	if err != nil {
		return Response(c, http.StatusInternalServerError, "failed to create media", err.Error())
	}
	if verrs.HasAny() {
		return Response(c, http.StatusUnprocessableEntity, "validation failed", verrs)
	}

	return Response(c, http.StatusCreated, "media created successfully", media)
}

// Update mengubah data media
func (v MediaResource) Update(c buffalo.Context) error {
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return Response(c, http.StatusInternalServerError, "Database connection not found", nil)
	}

	// Ambil data media lama dari database
	media := &models.Media{}
	if err := tx.Find(media, c.Param("media_id")); err != nil {
		return Response(c, http.StatusNotFound, "Media not found", nil)
	}

	oldFile := media.Img_Url // Simpan URL file lama

	// Bind input baru ke struct sementara
	var input models.Media
	if err := c.Bind(&input); err != nil {
		return Response(c, http.StatusBadRequest, "Invalid media data", nil)
	}

	// Cek apakah file berubah
	if input.Img_Url != "" && input.Img_Url != oldFile {
		// Hapus file lama dari MinIO
		if oldFile != "" {
			key := v.storageService.ExtractObjectKey(oldFile, v.storageService.Bucket)
			if key != "" {
				if err := v.storageService.Delete(c.Request().Context(), key); err != nil {
					log.Printf("⚠️ gagal hapus file lama di MinIO: %v", err)
					// Tidak menghentikan proses update meskipun gagal hapus file
				}
			}
		}
	}

	// Update field media
	media.Title = input.Title
	media.Img_Url = input.Img_Url
	media.CategoryID = input.CategoryID

	// Simpan perubahan ke database
	verrs, err := tx.ValidateAndUpdate(media)
	if err != nil {
		return Response(c, http.StatusInternalServerError, "Failed to update media", err.Error())
	}
	if verrs.HasAny() {
		return Response(c, http.StatusUnprocessableEntity, "Validation error", verrs)
	}

	return Response(c, http.StatusOK, "Media updated successfully", media)
}


// Destroy menghapus media
func (v MediaResource) Destroy(c buffalo.Context) error {
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return Response(c, http.StatusInternalServerError, "no transaction found", nil)
	}

	media := &models.Media{}
	if err := tx.Find(media, c.Param("media_id")); err != nil {
		return Response(c, http.StatusNotFound, "media not found", err.Error())
	}

	if media.Img_Url != "" {
		key := v.storageService.ExtractObjectKey(media.Img_Url, v.storageService.Bucket)

		if err := v.storageService.Delete(c.Request().Context(), key); err != nil {
			log.Printf("⚠️ gagal hapus file di MinIO: %v", err)
			// Tidak langsung return error — file bisa saja sudah hilang, tapi record tetap dihapus
		}
	}

	if err := tx.Destroy(media); err != nil {
		return Response(c, http.StatusInternalServerError, "failed to delete media", err.Error())
	}

	return Response(c, http.StatusOK, "media deleted successfully", nil)
}


// UploadImage mengunggah gambar ke storage
func (v MediaResource) UploadImage(c buffalo.Context) error {
	file, err := c.File("image")
	if err != nil {
		return Response(c, http.StatusBadRequest, "failed to read image file", err.Error())
	}
	defer file.Close()

	buf, _ := io.ReadAll(file)

	
	url, err := v.storageService.Upload(c.Request().Context(), "media/"+ uuid.New().String() + file.Filename, buf)
	if err != nil {
		return Response(c, http.StatusInternalServerError, "failed to upload image", err.Error())
	}

	return Response(c, http.StatusOK, "upload success", map[string]string{
		"url": url,
	})
}